apiVersion: v1
kind: Service
metadata:
  name: dns-test-service
  namespace: llmd-stack
spec:
  clusterIP: None  # <-- This makes it a Headless Service
  selector:
    app: dns-test
  ports:
    - name: dummy
      port: 1234
      targetPort: 1234
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dns-test
  namespace: llmd-stack
spec:
  serviceName: "dns-test-service"
  replicas: 2
  selector:
    matchLabels:
      app: dns-test
  template:
    metadata:
      labels:
        app: dns-test
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: ["/bin/sh", "-c", "sleep 3600"]