{{- if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llm-d-gateway-monitor
  namespace: {{ .Values.postgres.namespace }}
  labels:
    release: {{ .Values.servicemonitor.prometheusReleaseName }}
spec:
  selector:
    matchLabels:
      llm-d.ai/igw-mode: llm-d-router-gateway
  endpoints:
  - port: metrics-19001
    path: /metrics
{{- end }}