{{- if .Values.nvno.rdmaSharedDevicePlugin.enabled }}
# Depends on the Nvidia Network Operator
apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  name: nic-cluster-policy
spec:
  # Installs the RDMA Shared Device Plugin to expose HCA devices
  rdmaSharedDevicePlugin:
    image: k8s-rdma-shared-dev-plugin
    repository: ghcr.io/mellanox
    version: v1.5.2
    config: |
{{ .Values.nvno.rdmaSharedDevicePlugin.config | indent 6 }}
{{- end }}